version: '2'
services:
    dhu-app:
        image: dhu
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://dhu-mariadb:3306/dhu
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dhu-mariadb:
        extends:
            file: mariadb.yml
            service: dhu-mariadb
